---
product_name: ReSharper
#product_version: 1.0
product_type: DevGuide

# Specify the base url of the site. This is the path to the root of the site once
# it's been deployed. MUST have a trailing slash. Root should be '/'
baseurl: /help/resharper/sdk/
