---
product_name: ReSharper
#product_version: 1.0
product_type: DevGuide

url: https://www.jetbrains.com
# Specify the base url of the site. This is the path to the root of the site once
# it's been deployed. MUST have a trailing slash. Root should be '/'
baseurl: /help/resharper/sdk/

description: Documentation for writing extensions for ReSharper

github_repo: JetBrains/resharper-devguide
youtrack_project: RSRP
